#!/bin/sh
echo "=== Test01.sil ==="
java -classpath ./bin Sili < test01.sil
echo "=== Test02.sil ==="
java -classpath ./bin Sili < test02.sil
echo "=== Test03.sil ==="
java -classpath ./bin Sili < test03.sil
echo "=== Test04.sil ==="
java -classpath ./bin Sili < test04.sil
echo "=== Test05.sil ==="
java -classpath ./bin Sili < test05.sil
echo "=== Test06.sil ==="
java -classpath ./bin Sili < test06.sil
echo "=== Test07.sil ==="
java -classpath ./bin Sili < test07.sil
echo "=== Test08.sil ==="
java -classpath ./bin Sili < test08.sil
echo "=== Test09.sil ==="
java -classpath ./bin Sili < test09.sil
echo "=== Test10.sil ==="
java -classpath ./bin Sili < test10.sil
echo "=== Test11.sil ==="
java -classpath ./bin Sili < test11.sil
echo "=== TestMath.sil ==="
java -classpath ./bin Sili < test-math.sil

